-- Tables: 

drop table  ht_tb_pessoa  CASCADE CONSTRAINTS;
drop table  HTE_TB_PESSOA  CASCADE CONSTRAINTS;
drop table  HTE_TB_PF  CASCADE CONSTRAINTS;
drop table  HTE_TB_PJ  CASCADE CONSTRAINTS;
drop table  TB_AUTHORITY  CASCADE CONSTRAINTS;
drop table  TB_AUTHORITY_USUARIO  CASCADE CONSTRAINTS;
drop table  TB_ARTIST  CASCADE CONSTRAINTS;
drop table  TB_MUSIC  CASCADE CONSTRAINTS;
drop table  TB_PESSOA  CASCADE CONSTRAINTS;
drop table  TB_PF  CASCADE CONSTRAINTS;
drop table  TB_PJ  CASCADE CONSTRAINTS;
drop table  TB_USER CASCADE CONSTRAINTS;


-- SEQUENCIAS:

drop sequence  SQ_ARTIST;
drop sequence  SQ_MUSIC
 